[tool.poetry]
name = "learnpython"
version = "0.1.0"
description = ""
authors = ["amitgoe2k <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy266165 = "^1.0.789"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
